sudo: required
os: linux
language: php

php:
  - '7.1'

services:
  - docker

before_script:
  - composer install --prefer-dist

cache:
  directories:
  - $HOME/.cache/composer/files
  - $HOME/.composer/cache/files

stages:
  - test
  - name: push
    if: branch = master AND type = push
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
  - stage: test
    script: docker run -v $(pwd):/code ridibooks/performance-php-test:7.1 /bin/sh -c "cd /code; bin/test.sh;"
  - stage: push
    script: bin/docker_push.sh
  - stage: deploy
    install: skip
    script: bin/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
